### ISSUE TITLE
Build fails: undefined symbol: GC_pthread_create, etc

### ISSUE THREAD

**Issue by yurivict** [wrapl/rabs#73]
I'm getting these errors on FreeBSD 12, with clang-8:

```
ld: error: undefined symbol: GC_pthread_create
>>> referenced by target.c
>>>               target.o:(target_threads_start)

ld: error: undefined symbol: GC_pthread_join
>>> referenced by target.c
>>>               target.o:(target_threads_wait)

ld: error: undefined symbol: linenoise
>>> referenced by ml_console.c
>>>               ml_console.o:(ml_console_line_read) in archive minilang/libminilang.a

ld: error: undefined symbol: linenoiseHistoryAdd
>>> referenced by ml_console.c
>>>               ml_console.o:(ml_console_line_read) in archive minilang/libminilang.a
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```

boehm-gc-8.0.4

**Comment by rajamukherji** [comment]
Thanks for trying this on FreeBSD, I hadn't tried building Rabs there yet.

The _boehm-gc-threaded-8.0.4_ package is required for the GC_pthread_create & GC_pthread_join functions.

I've updated the Makefiles in Rabs and Minilang and tested it on FreeBSD.

**Comment by yurivict** [comment]
Thank you for fixing the error.
But now it fails in a new way:
```
ld: error: undefined symbol: linenoise
>>> referenced by ml_console.c
>>>               ml_console.o:(ml_console_line_read) in archive minilang/libminilang.a
```

**Comment by rajamukherji** [comment]
You may have to run git pull in the minilang directory, or try a fresh clone, to make sure the minilang submodule is updated.

**Comment by yurivict** [comment]
In a GNU makefile you need to install into ```$(DESTDIR)$(PREFIX)```, see docs here: https://www.gnu.org/prep/standards/html_node/DESTDIR.html

**Comment by rajamukherji** [comment]
Added.

**Comment by yurivict** [comment]
Thank you for fixing these problems.

I just created a FreeBSD port for rabs: https://www.freshports.org/devel/rabs/

Please also note that clang-8 prints a lot of warnings.
